name: Build Branches

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.16'

      - name: Install dependencies
        run: cpanm --installdeps .

      - name: Run prove
        run: prove -lv t
