name: Build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl: [
        '5.28',
        '5.30',
        '5.32',
        '5.34',
        '5.36',
        '5.38'
        ]

    name: Perl ${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Perl ${{ matrix.perl }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -V

      - name: Install dependencies
        run: cpanm --installdeps .

      - name: Run prove
        run: prove -lv t
